### PR TITLE
Add Highlight and fix open/save issue

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by pH-7** [comment]
Right now, I don't have the correct environment setup for testing it. @ehermellin Is this has been tested?

**Comment by ghost** [comment]
I have just checked and everything work find on my laptop !

**Comment by pH-7** [comment]
@ehermellin Brilliant!!

**Comment by pH-7** [comment]
Looks good to me! Thanks a lot for your contribution @ehermellin!

**Pull request merged**
