### PR TITLE
Added check if need to save file when click open button.

### PR DESCRIPTION
**Pull request by Matthew22877288287**
I added basic functionality if need to save a file when clicks "open"file.

### CODE REVIEW

**Review by pH-7 — CHANGES_REQUESTED** [review]
Can you exclude the *.png icon files? They are in `icons` folder. Not sure how they endup in the `src` directory.

**Comment by pH-7** [comment]
Thanks very much for this great improvement @Matthew22877288287! 💯
Before I merge your PR, can you have a look at my requested changes? Everything else looks good 😉

**Comment by Matthew22877288287** [comment]
I deleted the duplicate icon files in src folder.

**Review by pH-7 — APPROVED** [review]
💯

**Pull request merged**
