### PR TITLE
[WIP]-Some Auto Complete Functionalities

### PR DESCRIPTION
**Pull request by patrick-slagle**
This implements some code completion functionalities for the Simple Java Text Editor program. I like this editor so I added this to help with java programming. It provides code completion for Java keywords, brackets and parentheses. There may be a small bug or two so this is a work in progress and I hope to perfect it as issues arise. Any feedback on how this was implemented or ways to improve it is welcome.

### CODE REVIEW

**Comment by patrick-slagle** [comment]
I forgot to mention this but I changed tab indentation to 2 in UI.java as well. The smaller indentation looked better when coding.

**Comment by pH-7** [comment]
Okay, thank you very much for your contribution Patrick! Always welcome! I will test it this weekend. On what Java version did you run it?

P.S. You added a temporary file in your commit `src/simplejavatexteditor/UI.java~`

**Comment by patrick-slagle** [comment]
Thank you for pointing that out, the temp file is deleted. I used Java 1.8.0.51 to be exact. I believe it's the latest version of Java 8. I am actually still working with this as well. I'd like the auto complete to be compatible with multiple languages. So, you might get another pull request from me in the near future. When you test it, remember the code completion will only work if the file you're working on has been saved as a ".java" file.

Glad to contribute. It's a handy editor.

Thanks,
Patrick

**Comment by pH-7** [comment]
Very well Patrick! And very nice commits (details). I tested and was working OK but I didn't do any legitimate Q/A. So let me know if you are still working on this branch or aren't WIP anymore

**Comment by patrick-slagle** [comment]
Thank you very much. Glad to be of service.

I just finished it. What I wanted to do was make it compatible with multiple languages, not just Java. So, I made a separate class for the keywords and made it so you could kind of plug them into the auto complete class. I did find a bug as well. If you saved the file with a supported extension twice it would have two listeners on the text area and it just looked bad. I fixed that as well. It's reasonably simple for keyword support to be added to it, which is good. I have Java and C++ keywords in there now. If the user saves it as a .cpp extension it will now have C++ keyword suggestions. It can be expanded to support pretty much any number of languages.

**Comment by pH-7** [comment]
Hi again! Very sorry for the delay but was quite busy! Okay, super for that! Your branch got conflict with https://github.com/pH-7/Simple-Java-Text-Editor/pull/4/files (branch I merged just after you created this PR) so I have fixed the conflict here -> https://github.com/pH-7/Simple-Java-Text-Editor/pull/6

Please just review it (if I didn't do anything wrong, I've done it quite quick). If it's OK just give a :+1:  and I will merge it right away.

Again, thanks for your help. I really appreciate Patrick! Have a good Easter

**Comment by patrick-slagle** [comment]
No problem. Gad to help! Happy easter to you too. Giving the +1 now.

**Pull request closed without merging**
